import os
from termcolor import colored


class write_information_python:
    def main():
        a1 = 'import os'
        a2 = 'from termcolor import colored'
        a3_0 = 'import print_user'
        a3 = 'class Information_package:'
        a4 = '    def main():'
        a5 = '        directory_is_information_file = input(\'Введите директорию файла "information" :\')'
        a6 = '        if os.path.exists(directory_is_information_file):'
        a7 = '            with open(directory_is_information_file, \'r\') as file:'
        a8 = '                lines = file.readlines()'
        a9 = '            with open(\'setup_cashe/package/name_package.txt\', \'w\') as name_package:'
        a10 = '                name_package.write(lines[0])'
        a11 = '            with open(\"setup_cashe/package/version_package.", \'w\') as version_package:'
        a12 = '                 version_package.write(lines[1])'
        a13 = '            with open("setup_cashe/package/url_package.txt", "w") as url_package:'
        a14_0 = '                 url_package.write(lines[2])'
        a14 = '            print_user.dowloaded_package.main()'
        a15 = 'class File_package:'
        a16 = '    def main():'
        a17 = '        directory_setup.list_file = input(\'Введите директорию файла "setup.list" :\')'
        a18 = '        if os.path.exists(directory_setup-list_file):'
        a19 = '            with open(directory_setup-list_file, \'r\') as file:'
        a20 = '                lines = file.read().split("n")'
        a21 = '        else:'
        a22 = '            print(colored(\'Отсутствует директория файла "setup.list"\',\'red\'))'
        a23 = '            input(\'\\n\\nДля продолжения нажмите ENTER\')'
        a24 = '            sys.exit()'
        a25 = '        try:'
        a26 = '            print(colored(\'\\n\\n\\nstart install package\',\'green\'))'
        a27 = '            #index = количество строк в файле setup.list'
        a28 = '            index_input = len(lines)'
        a29 = '            index_input = int(index_input)'
        a30 = '            index_output = 0'
        a31 = '            while index_input!= index_output:'
        a32 = '                if index_input!= index_output:'
        a33 = '                    name = lines[index_output]'
        a34 = '                    with open(\'setup_cashe/file\', \'w\') as fp:'
        a35 = '                        fp.write(name)'
        a36 = '                    print_user.copy_package.main(name)'
        a37 = '                    index_output += 1'
        a38 = '        except Exception as e:'
        a39 = '            print(colored(\'Error install package\',\'red\'))'
        a40 = '            print(e)'
        a41 = '            input(\'\\n\\nДля продолжения нажмите ENTER\')'
        a42 = '            sys.exit()'
        a43 = '    print(colored(\'end install package\',\'green\'))'
        a44 = 'class Install_package:'
        a45 = '    def main():'
        a46 = '        print_user.install_package.main()'
        a47 = 'Information_package.main()'
        a48 = 'File_package.main()'
        a49 = 'Install_package.main()'

        with open('information_fake.py','w') as fp:
            fp.write(a1 + '\n' + a2 + '\n' + a3_0 + '\n' + a3 + '\n' + a4 + '\n' + a5 + '\n' + a6 + '\n' + a7 + '\n' + a8 + '\n' + a9 + '\n' + a10 + '\n' + a11 + '\n' + a12 + '\n' + a13 + '\n' + a14_0 + '\n' + a14 + '\n' + a15 + '\n' + a16 + '\n' + a17 + '\n' + a18 + '\n' + a19 + '\n' + a20 + '\n' + a21 + '\n' + a22 + '\n' + a23 + '\n' + a24 + '\n' + a25 + '\n' + a26 + '\n' + a27 + '\n' + a28 + '\n' + a29 + '\n' + a30 + '\n' + a31 + '\n' + a32 + '\n' + a33 + '\n' + a34 + '\n' + a35 + '\n' + a36 + '\n' + a37 + '\n' + a38 + '\n' + a39 + '\n' + a40 + '\n' + a41 + '\n' + a42 + '\n' + a43 + '\n' + a44 + '\n' + a45 + '\n' + a46 + '\n' + a47 + '\n' + a48 + '\n' + a49 + '\n')


class write_print_user_python:
    def main():
        a1 = 'import os'
        a2 = 'import sys'
        a3 = 'import shutil'
        a4 = 'from termcolor import colored'
        a5 = 'class dowloaded_package:'
        a6 = '    def main():'
        a7 = '        print(colored(\'start function dowloaded package\',\'green\'))'
        a8 = '        with open(\'setup_cashe/package/url_package.txt\', \'r\') as file:'
        a9 = '            url_package = file.read().strip()'
        a10 = '        try:'
        a11 = '            os.system(\'git clone \' + url_package)'
        a12 = '        except:'
        a13 = '            print(colored(\'Error git clone \'+ url_package,\'red\'))'
        a14 = '            input(\'\\n\\nДля продолжения нажмите ENTER\')'
        a15 = '            sys.exit()'
        a16 = '        print(colored(\'end function dowloaded package\',\'green\'))'
        a17 = 'class copy_package:'
        a18 = '    def main(name):'
        a19 = '        with open(\'setup_cashe/package/name_package.txt\', \'r\') as name_package:'
        a20 = '            name_package = name_package.read().strip()  # удалить символ новой строки'
        a21 = '        try:'
        a22 = '            ishod_dir = name_package + \'/\' + name'
        a23 = '            copy_dir = \'package/\' + name'
        a24 = '            print(\'     => copy \'+ name)'
        a25 = '            shutil.move(ishod_dir, copy_dir)'
        a26 = '        except Exception as e:'
        a27 = '            print(colored(\'Error copy package\',\'red\'))'
        a28 = '            print(e)'
        a29 = '            input(\'\\n\\nДля продолжения нажмите ENTER\')'
        a30 = '            sys.exit()'
        a31 = '        print(colored(\'end copy package\',\'green\'))'
        a32 = 'class install_package:'
        a33 = '    def main():'
        a34 = '        with open(\'setup_cashe/package/name_package.txt\', \'r\') as name_package:'
        a35 = '            name_package = name_package.read().strip(\'\\n\')  # удалить символ новой строки'
        a36 = '        print(colored(\'start install package\',\'green\'))'
        a37 = '        if os.path.exists(name_package + \'/install.py\'):'
        a38 = '            try:'
        a39 = '                os.system(\'python \' + name_package + \'/install.py\')'
        a40 = '            except Exception as e:'
        a41 = '                print(f\'\\n\' + {e})'
        a42 = '                print(colored(\'Error install package\',\'red\'))'
        a43 = '                input(\'\\n\\nДля продолжения нажмите ENTER\')'
        a44 = '                sys.exit()'
        a45 = '            print(colored(\'end install package\',\'green\'))'
        a46 = '        else:'
        a47 = '            if os.path.exists(\'install\'):'
        a48 = '                try:'
        a49 = '                    os.system(\'sudo chmod +x \\"./install\\"\')'
        a50 = '                    os.system(\'./install\')'
        a51 = '                except Exception as e:'
        a52 = '                    print(f\'\\n\' + {e})'
        a53 = '                    print(colored(\'Error install package\',\'red\'))'
        a54 = '                    input(\'\\n\\nДля продолжения нажмите ENTER\')'
        a55 = '                    sys.exit()'
        a56 = '                print(colored(\'end install package\',\'green\'))'
        
        write = a1 + '\n' + a2 + '\n' + a3 + '\n' + a4 + '\n' + a5 + '\n' + a6 + '\n' + a7 + '\n' + a8 + '\n' + a9 + '\n' + a10 + '\n' + a11 + '\n' + a12 + '\n' + a13 + '\n' + a14 + '\n' + a15 + '\n' + a16 + '\n' + a17 + '\n' + a18 + '\n' + a19 + '\n' + a20 + '\n' + a21 + '\n' + a20 + '\n' + a22 + '\n' + a23 + '\n' + a24 + '\n' + a25 + '\n' + a26 + '\n' + a27 + '\n' + a28 + '\n' + a29 + '\n' + a30 + '\n' + a31 + '\n' + a32 + '\n' + a33 + '\n' + a34 + '\n' + a35 + '\n' + a36 + '\n' + a37 + '\n' + a38 + '\n' + a39 + '\n' + a40 + '\n' + a41 + '\n' + a42 + '\n' + a43 + '\n' + a44 + '\n' + a45 + '\n' + a46 + '\n' + a47 + '\n' + a48 + '\n' + a49 + '\n' + a50 + '\n' + a51 + '\n' + a52 + '\n' + a53 + '\n' + a54 + '\n' + a55 + '\n' + a56
        with open('print_user_fake.py', 'w') as fp:
            fp.write(write)

write_information_python.main()